# Generated by Django 3.0.5 on 2020-04-27 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_class', models.PositiveSmallIntegerField(choices=[(0, 'Knight'), (1, 'Archer'), (2, 'Sorcerer')], default=0)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('attack_dmg', models.PositiveSmallIntegerField(default=10)),
                ('defence', models.PositiveSmallIntegerField(default=10)),
                ('hp', models.PositiveSmallIntegerField(default=100)),
                ('mana', models.PositiveSmallIntegerField(default=50)),
                ('stamina', models.PositiveSmallIntegerField(default=100)),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Others'), (1, 'Sword'), (2, 'Bow'), (3, 'Wand'), (4, 'Leather'), (5, 'Bow'), (6, 'Sorcerer robe'), (9, 'Consumables')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('bonus_attack_dmg', models.PositiveSmallIntegerField(default=0)),
                ('bonus_defence', models.PositiveSmallIntegerField(default=0)),
                ('bonus_hp', models.PositiveSmallIntegerField(default=0)),
                ('bonus_mana', models.PositiveSmallIntegerField(default=0)),
                ('bonus_stamina', models.PositiveSmallIntegerField(default=0)),
                ('items', models.ManyToManyField(related_name='items', to='TheInimicalWood.Character')),
            ],
        ),
    ]
