# Generated by Django 3.0.5 on 2020-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0002_remove_item_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(related_name='items', to='TheInimicalWood.Hero'),
        ),
    ]
