# Generated by Django 3.0.5 on 2020-04-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0003_auto_20200422_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
    ]
