# Generated by Django 3.0.5 on 2020-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0004_remove_item_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(related_name='items', to='TheInimicalWood.Hero'),
        ),
    ]
