# Generated by Django 3.0.5 on 2020-04-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0006_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='belongs_to_hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TheInimicalWood.Character'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
