# Generated by Django 3.0.5 on 2020-04-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0006_auto_20200423_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='avatar',
        ),
    ]
