# Generated by Django 3.0.5 on 2020-05-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0007_auto_20200429_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
    ]
