# Generated by Django 3.0.5 on 2020-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0007_remove_hero_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='playable',
            field=models.BooleanField(default=True),
        ),
    ]
