# Generated by Django 3.0.5 on 2020-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0010_auto_20200507_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='belongs_to_hero',
        ),
        migrations.AddField(
            model_name='item',
            name='belongs_to_hero',
            field=models.ManyToManyField(to='TheInimicalWood.Character'),
        ),
    ]
