# Generated by Django 3.0.5 on 2020-05-12 18:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0013_character_backpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backpack',
            field=jsonfield.fields.JSONField(),
        ),
    ]
