# Generated by Django 3.0.5 on 2020-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0014_auto_20200512_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backpack',
            field=models.TextField(),
        ),
    ]
