# Generated by Django 3.0.5 on 2020-05-12 19:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0016_auto_20200512_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backpack',
            field=jsonfield.fields.JSONField(),
        ),
    ]
