# Generated by Django 3.0.5 on 2020-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0017_auto_20200512_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='money',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
