# Generated by Django 3.0.5 on 2020-05-15 18:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0018_character_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
