# Generated by Django 3.0.5 on 2020-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0019_character_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Others'), (1, 'Sword'), (2, 'Bow'), (3, 'Wand'), (4, 'Leather'), (5, 'Bow'), (6, 'Helmet'), (7, 'Consumables')], default=0),
        ),
    ]
