# Generated by Django 3.0.5 on 2020-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0021_auto_20200518_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_hp',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='current_mana',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_current_hp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_current_mana',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
