# Generated by Django 3.0.5 on 2020-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0026_character_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.URLField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
